const API_BASE=window.REWARD_ASSIST_API||'https://rewards-assistant-api.mrgobeast.workers.dev';
const SERVICES=[
{id:'chick-fil-a',name:'Chick-fil-A',abbr:'CFA',color:'#ffe3e5',ink:'#b2182b',signup:'Account signup',birthday:'Birthday reward'},
{id:'nothing-bundt-cakes',name:'Nothing Bundt Cakes',abbr:'NBC',color:'#e9f5ef',ink:'#1d6754',signup:'eClub signup',birthday:'Birthday Bundtlet'},
{id:'crumbl',name:'Crumbl',abbr:'C',color:'#ffe8f1',ink:'#8f3155',signup:'Account signup',birthday:'Confirm current offer in app'},
];
const DEFAULT_PROFILE={firstName:'',birthday:'',services:SERVICES.map(s=>s.id),accounts:[]};
const state={mode:'login',token:localStorage.getItem('ra_token')||'',email:localStorage.getItem('ra_email')||'',key:null,version:Number(localStorage.getItem('ra_version')||0),profile:{...DEFAULT_PROFILE}};
const $=id=>document.getElementById(id);
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,options={}){const response=await fetch(API_BASE+path,{...options,headers:{'content-type':'application/json',...(state.token?{authorization:`Bearer ${state.token}`}:{}) ,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Something went wrong.');return data}
async function deriveKey(password,email){const bytes=new TextEncoder();const material=await crypto.subtle.importKey('raw',bytes.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:bytes.encode(`reward-assist:${email.toLowerCase()}`),iterations:100000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
function keyDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open('reward-assist-secure',1);request.onupgradeneeded=()=>request.result.createObjectStore('keys');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function saveDeviceKey(key){const db=await keyDb();await new Promise((resolve,reject)=>{const tx=db.transaction('keys','readwrite');tx.objectStore('keys').put(key,'vault');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function loadDeviceKey(){const db=await keyDb();return new Promise((resolve,reject)=>{const request=db.transaction('keys').objectStore('keys').get('vault');request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>reject(request.error)})}
async function clearDeviceKey(){const db=await keyDb();await new Promise((resolve,reject)=>{const tx=db.transaction('keys','readwrite');tx.objectStore('keys').delete('vault');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
const b64=bytes=>btoa(String.fromCharCode(...bytes));const unb64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
async function encryptProfile(){const iv=crypto.getRandomValues(new Uint8Array(12));const plain=new TextEncoder().encode(JSON.stringify(state.profile));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},state.key,plain);return JSON.stringify({v:1,iv:b64(iv),data:b64(new Uint8Array(encrypted))})}
async function encryptData(value){const iv=crypto.getRandomValues(new Uint8Array(12));const plain=new TextEncoder().encode(JSON.stringify(value));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},state.key,plain);return JSON.stringify({v:1,iv:b64(iv),data:b64(new Uint8Array(encrypted))})}
async function decryptProfile(payload){const box=JSON.parse(payload);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},state.key,unb64(box.data));return JSON.parse(new TextDecoder().decode(plain))}
function saveLocal(){localStorage.setItem('ra_profile',JSON.stringify(state.profile));localStorage.setItem('ra_version',String(state.version))}
function loadLocal(){try{state.profile={...DEFAULT_PROFILE,...JSON.parse(localStorage.getItem('ra_profile')||'{}')}}catch{state.profile={...DEFAULT_PROFILE}}}
function setSync(text){$('syncState').textContent=text}
async function pullVault(){try{setSync('Syncing…');const data=await api('/api/vault');if(data.vault){state.profile={...DEFAULT_PROFILE,...await decryptProfile(data.vault.payload)};state.version=data.vault.version;saveLocal()}else if(localStorage.getItem('ra_profile'))await pushVault();setSync('Synced');render()}catch(error){setSync('Saved on this device');toast(error.message)}}
async function pushVault(){saveLocal();if(!state.token||!state.key)return;try{setSync('Syncing…');const data=await api('/api/vault',{method:'PUT',body:JSON.stringify({payload:await encryptProfile(),expected_version:state.version})});state.version=data.version;saveLocal();setSync('Synced')}catch(error){setSync('Sync paused');toast(error.message)}}
function birthdayDays(date){if(!date)return null;const b=new Date(`${date}T12:00:00`),today=new Date();let next=new Date(today.getFullYear(),b.getMonth(),b.getDate(),12),start=new Date(today.getFullYear(),today.getMonth(),today.getDate(),12);if(next<start)next.setFullYear(next.getFullYear()+1);return Math.round((next-start)/86400000)}
function birthdayLabel(){if(!state.profile.birthday)return 'Birthday not added';return new Date(`${state.profile.birthday}T12:00:00`).toLocaleDateString(undefined,{month:'long',day:'numeric'})}
function render(){const days=birthdayDays(state.profile.birthday);$('welcomeTitle').textContent=state.profile.firstName?`Good to see you, ${state.profile.firstName}.`:'Good to see you.';$('nextRewardName').textContent=days===null?'Add your birthday to begin':days===0?'Happy birthday!':`${days} day${days===1?'':'s'} until your birthday`;$('nextRewardDate').textContent=days===null?'We’ll count down for you.':birthdayLabel();$('nextRewardDays').textContent=days===null?'—':days===0?'Today':`${days}d`;$('serviceGrid').innerHTML=SERVICES.filter(s=>state.profile.services.includes(s.id)).map(s=>`<button class="service-card" data-service="${s.id}"><span class="service-logo" style="--brand:${s.color};--brand-ink:${s.ink}">${s.abbr}</span><span class="service-copy"><strong>${s.name}</strong><small>${s.birthday}</small></span><span class="countdown ${days===null?'locked':''}"><strong>${days===null?'🔒':days===0?'Now':days}</strong><small>${days===null?'Add date':days===0?'Ready':'days'}</small></span></button>`).join('')||'<button class="service-card" id="emptyAdd"><span class="service-logo">＋</span><span class="service-copy"><strong>Add a place</strong><small>Choose the rewards you use</small></span></button>';document.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>openService(button.dataset.service)));if($('emptyAdd'))$('emptyAdd').onclick=openProfile;$('serviceChoices').innerHTML=SERVICES.map(s=>`<label class="service-choice"><input type="checkbox" value="${s.id}" ${state.profile.services.includes(s.id)?'checked':''}>${s.name}</label>`).join('');$('firstName').value=state.profile.firstName||'';$('birthday').value=state.profile.birthday||''}
const birthdaySection=$('serviceGrid').closest('.section-block');birthdaySection.querySelector('.eyebrow').textContent='BIRTHDAY OPTIONS';birthdaySection.querySelector('h2').textContent='Birthday rewards';birthdaySection.insertAdjacentHTML('beforebegin','<section class="section-block"><div class="section-title"><div><p class="eyebrow">SYNCED ACCOUNT WALLET</p><h2>Logins & QR codes</h2></div><span id="deviceSyncBadge" class="status-pill">Same Reward Assist login</span></div><div class="service-actions"><button id="requestTaco" class="primary">Request Taco Bell setup</button><button id="requestDutch" class="secondary">Request Dutch Bros setup</button></div><div id="walletGrid" class="service-grid"></div></section>');
function renderWallet(){state.profile.accounts=state.profile.accounts||[];$('walletGrid').innerHTML=state.profile.accounts.length?state.profile.accounts.map((a,i)=>`<button class="service-card" data-wallet="${i}"><span class="service-logo" style="--brand:#e6edff;--brand-ink:#183c7a">${(a.program||a.app||'?').slice(0,2).toUpperCase()}</span><span class="service-copy"><strong>${a.program||a.app}</strong><small>${a.email||'Saved account'}</small></span><span class="countdown"><strong>View</strong><small>secure</small></span></button>`).join(''):'<div class="privacy-note">No accounts have synced yet. Send a setup request or complete an account in the Windows app.</div>';document.querySelectorAll('[data-wallet]').forEach(b=>b.onclick=()=>showWallet(Number(b.dataset.wallet)))}
function openWallet(){$('serviceDialogBody').innerHTML='<div class="dialog-head"><div><p class="eyebrow">ENCRYPTED WALLET</p><h2>Save a rewards account</h2></div><button class="close" data-close="serviceDialog">×</button></div><form id="walletForm"><label>Restaurant or program<input id="walletProgram" required placeholder="Taco Bell"></label><label>Login email<input id="walletEmail" type="email"></label><label>Password<input id="walletPassword" type="password"></label><label>Notes<input id="walletNotes"></label><label>QR code image<input id="walletQr" type="file" accept="image/png,image/jpeg,image/webp"></label><button class="primary full" type="submit">Encrypt, save, and sync</button></form>';$('serviceDialog').showModal();$('serviceDialogBody').querySelector('[data-close]').onclick=()=>$('serviceDialog').close();$('walletForm').onsubmit=saveWallet}
async function saveWallet(event){event.preventDefault();const file=$('walletQr').files[0];if(file&&file.size>1500000)return toast('Choose a QR image smaller than 1.5 MB.');const qr=file?await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file)}):'';state.profile.accounts.push({program:$('walletProgram').value.trim(),email:$('walletEmail').value.trim(),password:$('walletPassword').value,notes:$('walletNotes').value.trim(),qr});$('serviceDialog').close();renderWallet();await pushVault();toast('Account encrypted and synced')}
function showWallet(index){const a=state.profile.accounts[index];$('serviceDialogBody').innerHTML='<div class="dialog-head"><div><p class="eyebrow">SAVED ACCOUNT</p><h2>'+a.program+'</h2></div><button class="close" data-close="serviceDialog">×</button></div>'+(a.email?'<p><strong>Email:</strong> '+a.email+'</p>':'')+(a.password?'<p><strong>Password:</strong> <span id="savedPassword">••••••••</span> <button id="revealPassword" class="secondary" type="button">Show</button></p>':'')+(a.notes?'<p>'+a.notes+'</p>':'')+(a.qr?'<img src="'+a.qr+'" alt="Saved rewards QR" style="width:100%;border-radius:14px">':'<p>No QR image saved.</p>')+'<button id="deleteWallet" class="danger full">Delete account</button>';$('serviceDialog').showModal();$('serviceDialogBody').querySelector('[data-close]').onclick=()=>$('serviceDialog').close();if($('revealPassword'))$('revealPassword').onclick=()=>{$('savedPassword').textContent=a.password;$('revealPassword').remove()};$('deleteWallet').onclick=async()=>{if(!confirm('Delete this saved account?'))return;state.profile.accounts.splice(index,1);$('serviceDialog').close();renderWallet();await pushVault()}}
const baseRender=render;render=function(){baseRender();renderWallet()};$('requestTaco').onclick=()=>showSetupRequest('Taco Bell');$('requestDutch').onclick=()=>showSetupRequest('Dutch Bros');
function showSetupRequest(app){const dutch=app==='Dutch Bros';$('serviceDialogBody').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">SEND TO WINDOWS</p><h2>${app} setup</h2></div><button class="close" data-close="serviceDialog">×</button></div><p>The encrypted request waits safely if your computer is off and starts when the signed-in Windows app comes online.</p><form id="remoteSetupForm"><label>First name<input id="remoteFirst" required></label><label>Last name<input id="remoteLast" required></label><label>Email<input id="remoteEmail" required type="email" value="${state.email}"></label>${dutch?'<label>Phone<input id="remotePhone" required inputmode="tel"></label>':''}<label>ZIP code<input id="remoteZip" required inputmode="numeric" pattern="[0-9]{5}" maxlength="5"></label><label>Birthday<input id="remoteBirthday" required type="date" value="${state.profile.birthday||''}"></label><button class="primary full" type="submit">Queue encrypted request</button></form>`;$('serviceDialog').showModal();$('serviceDialogBody').querySelector('[data-close]').onclick=()=>$('serviceDialog').close();$('remoteSetupForm').onsubmit=async event=>{event.preventDefault();const details=['first_name: '+$('remoteFirst').value.trim(),'last_name: '+$('remoteLast').value.trim(),...(dutch?['phone: '+$('remotePhone').value.trim()]:[]),'email: '+$('remoteEmail').value.trim(),'zip_code: '+$('remoteZip').value.trim(),'birthday: '+$('remoteBirthday').value,'END'].join('\n');const encrypted_payload=await encryptData({details});try{await api('/api/tasks',{method:'POST',body:JSON.stringify({app,encrypted_payload})});$('serviceDialog').close();toast('Request queued for your Windows app')}catch(error){toast(error.message)}}}
function showAuth(){$('landingScreen').classList.add('hidden');$('authScreen').classList.remove('hidden');$('authEmail').focus()}
async function loadMessages(){try{const data=await api('/api/messages');if(data.messages?.length){const latest=data.messages[0];toast(`${latest.title}: ${latest.body}`)}}catch{}}
function showApp(){loadLocal();$('landingScreen').classList.add('hidden');$('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('accountEmail').textContent=state.email;$('accountButton').textContent=(state.email[0]||'A').toUpperCase();render();pullVault();loadMessages()}
function openProfile(){render();$('profileDialog').showModal()}
function openService(id){const s=SERVICES.find(item=>item.id===id),days=birthdayDays(state.profile.birthday);$('serviceDialogBody').innerHTML=`<div class="dialog-head"><div class="service-dialog-logo" style="--brand:${s.color};color:${s.ink}">${s.abbr}</div><button class="close" data-close="serviceDialog" aria-label="Close">×</button></div><h2>${s.name}</h2><span class="status-pill">${days===null?'Birthday locked — add a date':days===0?'Birthday reward ready':'Unlocks in '+days+' days'}</span><p><strong>Account:</strong> ${s.signup}</p><p><strong>Birthday:</strong> ${s.birthday}</p><div class="service-actions"><button class="primary" id="serviceSetup">Start guided signup</button><button class="secondary" id="serviceBirthday">Update birthday</button></div>`;$('serviceDialog').showModal();$('serviceDialogBody').querySelector('[data-close]').onclick=()=>$('serviceDialog').close();$('serviceBirthday').onclick=()=>{$('serviceDialog').close();openProfile()};$('serviceSetup').onclick=()=>toast(`${s.name} guided signup currently requires the Windows app.`)}
function showTacoRequest(){$('serviceDialogBody').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">SEND TO WINDOWS</p><h2>Create a Taco Bell account</h2></div><button class="close" data-close="serviceDialog" aria-label="Close">×</button></div><p>Your signed-in Windows computer must be on with Reward Assist open.</p><form id="tacoRequestForm"><label>First name<input id="tacoFirst" required autocomplete="given-name"></label><label>Last name<input id="tacoLast" required autocomplete="family-name"></label><label>Email<input id="tacoEmail" required type="email" autocomplete="email" value="${state.email}"></label><label>ZIP code<input id="tacoZip" required inputmode="numeric" pattern="[0-9]{5}" maxlength="5"></label><label>Birthday<input id="tacoBirthday" required type="date" value="${state.profile.birthday||''}"></label><button class="primary full" type="submit">Send securely to my Windows app</button></form><p class="privacy-note">You will enter the verification code yourself. Reward Assist never bypasses restaurant verification.</p>`;$('serviceDialogBody').querySelector('[data-close]').onclick=()=>$('serviceDialog').close();$('tacoRequestForm').onsubmit=async event=>{event.preventDefault();const details=['first_name: '+$('tacoFirst').value.trim(),'last_name: '+$('tacoLast').value.trim(),'email: '+$('tacoEmail').value.trim(),'zip_code: '+$('tacoZip').value.trim(),'birthday: '+$('tacoBirthday').value,'END'].join('\n');const button=event.submitter;button.disabled=true;button.textContent='Sending…';try{await api('/api/tasks',{method:'POST',body:JSON.stringify({app:'Taco Bell',details})});$('serviceDialog').close();toast('Sent to your Windows app')}catch(error){toast(error.message);button.disabled=false;button.textContent='Send securely to my Windows app'}}}
$('openWebApp').onclick=showAuth;$('backToDownloads').onclick=()=>{$('authScreen').classList.add('hidden');$('landingScreen').classList.remove('hidden')};$('iphoneInstall').onclick=()=>$('installDialog').showModal();
$('authMode').onclick=()=>{state.mode=state.mode==='login'?'signup':'login';$('authSubmit').textContent=state.mode==='login'?'Sign in':'Create account';$('authMode').textContent=state.mode==='login'?'New here? Create an account':'Already have an account? Sign in';$('authPassword').autocomplete=state.mode==='login'?'current-password':'new-password'};
$('authForm').onsubmit=async event=>{event.preventDefault();const email=$('authEmail').value.trim().toLowerCase(),password=$('authPassword').value,submit=$('authSubmit');submit.disabled=true;submit.textContent=state.mode==='login'?'Signing in…':'Creating…';try{const data=await api(`/api/auth/${state.mode}`,{method:'POST',body:JSON.stringify({email,password})});state.token=data.token;state.email=data.user.email;state.key=await deriveKey(password,email);await saveDeviceKey(state.key);localStorage.setItem('ra_token',state.token);localStorage.setItem('ra_email',state.email);showApp()}catch(error){toast(error.message)}finally{submit.disabled=false;submit.textContent=state.mode==='login'?'Sign in':'Create account'}};
$('editProfileButton').onclick=openProfile;$('profileForm').onsubmit=event=>{event.preventDefault();state.profile.firstName=$('firstName').value.trim();state.profile.birthday=$('birthday').value;state.profile.services=[...$('serviceChoices').querySelectorAll('input:checked')].map(i=>i.value);$('profileDialog').close();render();pushVault()};
$('accountButton').onclick=()=>$('accountDialog').showModal();document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$(button.dataset.close).close());$('logoutButton').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'})}catch{}await clearDeviceKey();localStorage.removeItem('ra_token');localStorage.removeItem('ra_email');state.token='';state.key=null;location.reload()};$('forceSync').onclick=()=>pullVault();$('showInstallHelp').onclick=()=>{$('accountDialog').close();$('installDialog').showModal()};document.querySelector('[data-view="add"]').style.display='none';document.querySelector('[data-view="account"]').onclick=()=>$('accountDialog').showModal();
let deferredInstall;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;$('installButton').classList.remove('hidden')});$('installButton').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else $('installDialog').showModal()};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));if(state.token){loadDeviceKey().then(key=>{if(key){state.key=key;showApp()}else{$('authEmail').value=state.email;$('authPassword').placeholder='Enter password once to unlock this device';showAuth()}}).catch(showAuth)}
