const API_BASE=window.REWARD_ASSIST_API||'https://rewards-assistant-api.mrgobeast.workers.dev';
const SERVICES=[
{id:'dutch-bros',name:'Dutch Bros',abbr:'DB',color:'#d7f2ff',ink:'#076e9b',signup:'Windows setup required',birthday:'Birthday drink'},
{id:'taco-bell',name:'Taco Bell',abbr:'TB',color:'#efe0ff',ink:'#5c1593',signup:'Online signup',birthday:'Birthday reward'},
{id:'chick-fil-a',name:'Chick-fil-A',abbr:'CFA',color:'#ffe3e5',ink:'#b2182b',signup:'Account signup',birthday:'Birthday reward'},
{id:'nothing-bundt-cakes',name:'Nothing Bundt Cakes',abbr:'NBC',color:'#e9f5ef',ink:'#1d6754',signup:'eClub signup',birthday:'Birthday Bundtlet'},
{id:'paris-baguette',name:'Paris Baguette',abbr:'PB',color:'#e2ebff',ink:'#234e9a',signup:'Rewards signup',birthday:'Birthday reward'}];
const DEFAULT_PROFILE={firstName:'',birthday:'',services:SERVICES.map(s=>s.id)};
const state={mode:'login',token:localStorage.getItem('ra_token')||'',email:localStorage.getItem('ra_email')||'',key:null,version:Number(localStorage.getItem('ra_version')||0),profile:{...DEFAULT_PROFILE}};
const $=id=>document.getElementById(id);
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
async function api(path,options={}){const response=await fetch(API_BASE+path,{...options,headers:{'content-type':'application/json',...(state.token?{authorization:`Bearer ${state.token}`}:{}) ,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||'Something went wrong.');return data}
async function deriveKey(password,email){const bytes=new TextEncoder();const material=await crypto.subtle.importKey('raw',bytes.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:bytes.encode(`reward-assist:${email.toLowerCase()}`),iterations:100000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
const b64=bytes=>btoa(String.fromCharCode(...bytes));const unb64=value=>Uint8Array.from(atob(value),c=>c.charCodeAt(0));
async function encryptProfile(){const iv=crypto.getRandomValues(new Uint8Array(12));const plain=new TextEncoder().encode(JSON.stringify(state.profile));const encrypted=await crypto.subtle.encrypt({name:'AES-GCM',iv},state.key,plain);return JSON.stringify({v:1,iv:b64(iv),data:b64(new Uint8Array(encrypted))})}
async function decryptProfile(payload){const box=JSON.parse(payload);const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(box.iv)},state.key,unb64(box.data));return JSON.parse(new TextDecoder().decode(plain))}
function saveLocal(){localStorage.setItem('ra_profile',JSON.stringify(state.profile));localStorage.setItem('ra_version',String(state.version))}
function loadLocal(){try{state.profile={...DEFAULT_PROFILE,...JSON.parse(localStorage.getItem('ra_profile')||'{}')}}catch{state.profile={...DEFAULT_PROFILE}}}
function setSync(text){$('syncState').textContent=text}
async function pullVault(){try{setSync('Syncing…');const data=await api('/api/vault');if(data.vault){state.profile={...DEFAULT_PROFILE,...await decryptProfile(data.vault.payload)};state.version=data.vault.version;saveLocal()}else if(localStorage.getItem('ra_profile'))await pushVault();setSync('Synced');render()}catch(error){setSync('Saved on this device');toast(error.message)}}
async function pushVault(){saveLocal();if(!state.token||!state.key)return;try{setSync('Syncing…');const data=await api('/api/vault',{method:'PUT',body:JSON.stringify({payload:await encryptProfile(),expected_version:state.version})});state.version=data.version;saveLocal();setSync('Synced')}catch(error){setSync('Sync paused');toast(error.message)}}
function birthdayDays(date){if(!date)return null;const b=new Date(`${date}T12:00:00`),today=new Date();let next=new Date(today.getFullYear(),b.getMonth(),b.getDate(),12),start=new Date(today.getFullYear(),today.getMonth(),today.getDate(),12);if(next<start)next.setFullYear(next.getFullYear()+1);return Math.round((next-start)/86400000)}
function birthdayLabel(){if(!state.profile.birthday)return 'Birthday not added';return new Date(`${state.profile.birthday}T12:00:00`).toLocaleDateString(undefined,{month:'long',day:'numeric'})}
function render(){const days=birthdayDays(state.profile.birthday);$('welcomeTitle').textContent=state.profile.firstName?`Good to see you, ${state.profile.firstName}.`:'Good to see you.';$('nextRewardName').textContent=days===null?'Add your birthday to begin':days===0?'Happy birthday!':`${days} day${days===1?'':'s'} until your birthday`;$('nextRewardDate').textContent=days===null?'We’ll count down for you.':birthdayLabel();$('nextRewardDays').textContent=days===null?'—':days===0?'Today':`${days}d`;$('serviceGrid').innerHTML=SERVICES.filter(s=>state.profile.services.includes(s.id)).map(s=>`<button class="service-card" data-service="${s.id}"><span class="service-logo" style="--brand:${s.color};--brand-ink:${s.ink}">${s.abbr}</span><span class="service-copy"><strong>${s.name}</strong><small>${s.birthday}</small></span><span class="countdown ${days===null?'locked':''}"><strong>${days===null?'🔒':days===0?'Now':days}</strong><small>${days===null?'Add date':days===0?'Ready':'days'}</small></span></button>`).join('')||'<button class="service-card" id="emptyAdd"><span class="service-logo">＋</span><span class="service-copy"><strong>Add a place</strong><small>Choose the rewards you use</small></span></button>';document.querySelectorAll('[data-service]').forEach(button=>button.addEventListener('click',()=>openService(button.dataset.service)));if($('emptyAdd'))$('emptyAdd').onclick=openProfile;$('serviceChoices').innerHTML=SERVICES.map(s=>`<label class="service-choice"><input type="checkbox" value="${s.id}" ${state.profile.services.includes(s.id)?'checked':''}>${s.name}</label>`).join('');$('firstName').value=state.profile.firstName||'';$('birthday').value=state.profile.birthday||''}
function showAuth(){$('landingScreen').classList.add('hidden');$('authScreen').classList.remove('hidden');$('authEmail').focus()}
function showApp(){loadLocal();$('landingScreen').classList.add('hidden');$('authScreen').classList.add('hidden');$('appShell').classList.remove('hidden');$('accountEmail').textContent=state.email;$('accountButton').textContent=(state.email[0]||'A').toUpperCase();render();pullVault()}
function openProfile(){render();$('profileDialog').showModal()}
function openService(id){const s=SERVICES.find(item=>item.id===id),days=birthdayDays(state.profile.birthday);$('serviceDialogBody').innerHTML=`<div class="dialog-head"><div class="service-dialog-logo" style="--brand:${s.color};color:${s.ink}">${s.abbr}</div><button class="close" data-close="serviceDialog" aria-label="Close">×</button></div><h2>${s.name}</h2><span class="status-pill">${days===null?'Birthday locked — add a date':days===0?'Birthday reward ready':'Unlocks in '+days+' days'}</span><p><strong>Account:</strong> ${s.signup}</p><p><strong>Birthday:</strong> ${s.birthday}</p><div class="service-actions"><button class="primary" id="serviceSetup">Start guided signup</button><button class="secondary" id="serviceBirthday">Update birthday</button></div>`;$('serviceDialog').showModal();$('serviceDialogBody').querySelector('[data-close]').onclick=()=>$('serviceDialog').close();$('serviceBirthday').onclick=()=>{$('serviceDialog').close();openProfile()};$('serviceSetup').onclick=()=>toast(`${s.name} guided signup currently requires the Windows app.`)}
function showTacoRequest(){$('serviceDialogBody').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">SEND TO WINDOWS</p><h2>Create a Taco Bell account</h2></div><button class="close" data-close="serviceDialog" aria-label="Close">×</button></div><p>Your signed-in Windows computer must be on with Reward Assist open.</p><form id="tacoRequestForm"><label>First name<input id="tacoFirst" required autocomplete="given-name"></label><label>Last name<input id="tacoLast" required autocomplete="family-name"></label><label>Email<input id="tacoEmail" required type="email" autocomplete="email" value="${state.email}"></label><label>ZIP code<input id="tacoZip" required inputmode="numeric" pattern="[0-9]{5}" maxlength="5"></label><label>Birthday<input id="tacoBirthday" required type="date" value="${state.profile.birthday||''}"></label><button class="primary full" type="submit">Send securely to my Windows app</button></form><p class="privacy-note">You will enter the verification code yourself. Reward Assist never bypasses restaurant verification.</p>`;$('serviceDialogBody').querySelector('[data-close]').onclick=()=>$('serviceDialog').close();$('tacoRequestForm').onsubmit=async event=>{event.preventDefault();const details=['first_name: '+$('tacoFirst').value.trim(),'last_name: '+$('tacoLast').value.trim(),'email: '+$('tacoEmail').value.trim(),'zip_code: '+$('tacoZip').value.trim(),'birthday: '+$('tacoBirthday').value,'END'].join('\n');const button=event.submitter;button.disabled=true;button.textContent='Sending…';try{await api('/api/tasks',{method:'POST',body:JSON.stringify({app:'Taco Bell',details})});$('serviceDialog').close();toast('Sent to your Windows app')}catch(error){toast(error.message);button.disabled=false;button.textContent='Send securely to my Windows app'}}}
$('openWebApp').onclick=showAuth;$('backToDownloads').onclick=()=>{$('authScreen').classList.add('hidden');$('landingScreen').classList.remove('hidden')};$('iphoneInstall').onclick=()=>$('installDialog').showModal();
$('authMode').onclick=()=>{state.mode=state.mode==='login'?'signup':'login';$('authSubmit').textContent=state.mode==='login'?'Sign in':'Create account';$('authMode').textContent=state.mode==='login'?'New here? Create an account':'Already have an account? Sign in';$('authPassword').autocomplete=state.mode==='login'?'current-password':'new-password'};
$('authForm').onsubmit=async event=>{event.preventDefault();const email=$('authEmail').value.trim().toLowerCase(),password=$('authPassword').value,submit=$('authSubmit');submit.disabled=true;submit.textContent=state.mode==='login'?'Signing in…':'Creating…';try{const data=await api(`/api/auth/${state.mode}`,{method:'POST',body:JSON.stringify({email,password})});state.token=data.token;state.email=data.user.email;state.key=await deriveKey(password,email);localStorage.setItem('ra_token',state.token);localStorage.setItem('ra_email',state.email);showApp()}catch(error){toast(error.message)}finally{submit.disabled=false;submit.textContent=state.mode==='login'?'Sign in':'Create account'}};
$('editProfileButton').onclick=openProfile;$('profileForm').onsubmit=event=>{event.preventDefault();state.profile.firstName=$('firstName').value.trim();state.profile.birthday=$('birthday').value;state.profile.services=[...$('serviceChoices').querySelectorAll('input:checked')].map(i=>i.value);$('profileDialog').close();render();pushVault()};
$('accountButton').onclick=()=>$('accountDialog').showModal();document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$(button.dataset.close).close());$('logoutButton').onclick=async()=>{try{await api('/api/auth/logout',{method:'POST',body:'{}'})}catch{}localStorage.removeItem('ra_token');localStorage.removeItem('ra_email');state.token='';state.key=null;location.reload()};$('forceSync').onclick=()=>pullVault();$('showInstallHelp').onclick=()=>{$('accountDialog').close();$('installDialog').showModal()};document.querySelector('[data-view="add"]').onclick=openProfile;document.querySelector('[data-view="account"]').onclick=()=>$('accountDialog').showModal();
let deferredInstall;window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredInstall=event;$('installButton').classList.remove('hidden')});$('installButton').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else $('installDialog').showModal()};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));if(state.token){$('authEmail').value=state.email;$('authPassword').placeholder='Enter password to unlock sync';showAuth()}
