const {chromium}=require('playwright'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
const page=await browser.newPage();await page.setContent(`<h1>You're Almost There</h1>${['first-name','last-name','email','zip','birthday','password','password-confirmation'].map(id=>`<input id="${id}">`).join('')}<button>The Shops at Highland Village (Highland Village, TX)</button><input type="checkbox" id="terms_and_conditions"><div style="height:40px"></div><button id="submit">SIGN UP</button>`);
await page.evaluate(()=>{window.reports=[];window.submits=0;document.querySelector('#submit').onclick=()=>submits++;window.task={active:true,session_id:'test',approved:false,claims:[],details:{first_name:'Test',last_name:'Example',email:'test@example.com',phone:'2025550147',zip_code:'75022',birthday:'1990-10-17',password:'TestingOnly123!',restaurant:'The Shops at Highland Village (Highland Village, TX)'}};window.chrome={runtime:{sendMessage:(m,cb)=>{if(m.type==='status'){reports.push(m.payload.stage);if(m.payload.stage.startsWith('claim_')){const claimed=!task.claims.includes(m.payload.stage);task.claims.push(m.payload.stage);cb({claimed});return}}cb(m.type==='task'?task:{ok:true})}}}});
await page.addScriptTag({path:path.join(__dirname,'../chrome_extension/cheesecake.js')});await page.waitForFunction(()=>reports.includes('review_required'));assert.equal(await page.locator('#birthday').inputValue(),'10/17/1990');assert.equal(await page.locator('#password-confirmation').inputValue(),'TestingOnly123!');assert(!await page.locator('#terms_and_conditions').isChecked());assert.equal(await page.evaluate(()=>submits),0);
await page.evaluate(()=>task.approved=true);await page.waitForFunction(()=>submits===1);assert(await page.locator('#terms_and_conditions').isChecked());await page.addScriptTag({path:path.join(__dirname,'../chrome_extension/cheesecake.js')});assert.equal(await page.evaluate(()=>submits),1);
await page.evaluate(()=>{task.claims=[];document.body.append(Object.assign(document.createElement('p'),{textContent:'Http failure response for /api/profiles: 400 OK'}))});await page.waitForFunction(()=>reports.includes('attention'));assert.equal(await page.evaluate(()=>submits),1);
console.log('PASS: profile fill, birthday format, consent approval gate, single submission and 400 failure stop');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
